name: laravellandodemo
recipe: laravel
services:
  appserver:
    type: php:8.0
    xdebug: true
  myservice:
    type: mysql:8.0
  pma:
    type: phpmyadmin
config:
  webroot: public
  database: mysql:8.0
